[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  SECRETS_SCAN_OMIT_PATHS = "dist/assets/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Service-Worker-Allowed = "/"
    Cache-Control = "no-store"
    Cross-Origin-Resource-Policy = "same-site"
    Cross-Origin-Opener-Policy = "same-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' data: https://js.stripe.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.sentry.io https://api.stripe.com https://driver-vehicle-licensing.api.gov.uk https://uk.api.vehicledataglobal.com;
      frame-src https://js.stripe.com;
    """

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
